### ISSUE TITLE
Revisit starter dependencies

### ISSUE THREAD

**Issue by snicoll** [pivotal-cf/spring-cloud-services-starters#22]
I realized yesterday a bit by accident that `spring-cloud-services-starter-config-client` alone was starting a web server. 

The current project structure looks weird to me. I'd strongly recommend you [not to add `dependencies` to a parent](https://github.com/pivotal-cf/spring-cloud-services-starters/blob/aa4cc312d146ef2535cdab6d230e2cb36d3c5021/spring-cloud-services-dependencies-parent/pom.xml#L69) as it makes it extremely difficult to track down what the (direct) dependencies of a particular starter is. I guess that this arrangement is partially the reason why something that isn't web related relies on the web starter.

As a side note, having stronger opinion for the user never was a best practice and is even more problematic now that the user can choose between the Servlet (`starter-web`)  and the Reactive (`starter-webflux`) stack.

**Comment by ojhughes** [comment]
Thanks for pointing this out, we will clean up these dependencies as part of `M2` release shortly

**Comment by royclarkson** [comment]
@snicoll I completely agree about removing the web starter. I'm also moving the remaining shared dependencies down to the individual starters as you recommend, so they are more readable and transparent. Regarding being strongly opinionated however, the SCS starters were always meant to be strongly opinionated because they are targeting a very specific use case of running apps on PCF with one of the SCS services. We have to continue to balance that goal with also providing as much flexibility as possible.

**Comment by snicoll** [comment]
@royclarkson thanks for the super quick feedback. I am fine with the idea that you have to be more opinionated than an "average" starter. 

Speaking of which:

> As a side note, having stronger opinion for the user never was a best practice

Apologizes, I mean to write "As a side note, having stronger opinion **on the web stack** never was a best practice". We did it for template engines in 1.x because they naturally relates to the web side of things and we've backed away from that now that WebFlux is also a valid choice.

What is the reason for associating config client with web app? Is this feature incompatible with WebFlux?

Thanks!

**Comment by royclarkson** [comment]
@snicoll at one point config client and server were intertwined and all three spring cloud services were web apps, which meant including the web starter made more sense. So it's a carryover for historic reasons that was never updated or addressed because everything kept working as expected in our tests. Regarding WebFlux, we're still in process of updating for spring boot 2.
