### ISSUE TITLE
2.1.2.RELEASE refers to artifacts not available on Maven Central

### ISSUE THREAD

**Issue by snicoll** [pivotal-cf/spring-cloud-services-starters#87]
The latest BOM refers to Spring Cloud Services connectors `2.1.1.RELEASE` but such version does not exist on Maven Central.

There is a `2.1.2.RELEASE` for `spring-cloud-services-cloudfoundry-connector` and `spring-cloud-services-spring-connector` though so perhaps the version should have been bumped?

This is currently breaking start.spring.io https://github.com/spring-io/start.spring.io/issues/103

**Comment by habuma** [comment]
Apparently, something went wrong pushing 2.1.1.RELEASE of connectors to Maven central. I've reattempted and now am waiting for the artifacts to arrive on Maven central. This should fix this issue.

There's still a question of why there are no starters that reference 2.1.2.RELEASE of connectors, but that's a separate issue (and one I'll be looking into). Once 2.1.1.RELEASE connectors appear in Maven central, this issue will be considered resolved.

FWIW, it's okay if our starter versions get out of sync with connector versions, which is why 2.1.2 starters point to 2.1.1 connectors. That happens when we bump a version in starters, but have nothing to release in connectors. It's not ideal, and I personally dislike it...I'd rather deploy an unchanged release of connectors and keep them in sync...but that's how it has been done.

**Comment by habuma** [comment]
The 2.1.1.RELEASE connector artifacts are now in Maven central and the ability to build with 2.1.2.RELEASE starters has been confirmed by myself and two others. So I'm going to consider this issue resolved.

Note that I would like the 2.1.2.RELEASE starters be reinstated in Initializr. But if #86 is one of the reasons for not doing that, then I understand and will be addressing that in a 2.1.3.RELEASE of starters. On the other hand, 2.1.0.RELEASE has the same issue, so bumping back up to 2.1.2.RELEASE in the interim would do no worse than leaving it on 2.1.0.RELEASE in that regard.

**Comment by habuma** [comment]
@snicoll Any thoughts on that last comment regarding reinstating 2.1.2.RELEASE in intializr?

**Comment by snicoll** [comment]
Thanks for the feedback. No problem Craig, we will reinstate to that version, I agree with your analysis.
